#!/usr/local/bin/php -Cq
<?php
class devCli
{
    /**
     * @var string
     */
    private $index = '/index.php';

    /**
     * @var string
     */
    private $cli_name = 'Quickly WebSite';

    /**
     * @var string
     */
    private $cli_version = 'dev-1.0.1';

    /**
     * @var array
     */
    private $inside_commend = ['-h', '-v', 'serv'];

    /**
     * @var array
     */
    private $inside_func = [
        '-v' => 'version',
        '-h' => 'usages',
        'serv' => 'serve'
    ];

    /**
     * @var string
     */
    private $command;

    /**
     * devCli constructor.
     * @param array $params
     */
    public function __construct($params = [])
    {
        if(PHP_SAPI !== 'cli') {
            $this->format('this file must be cli model',true);
        }
        array_shift($params);
        $this->command = $params[0] ?? '';
        if(!$this->command || !in_array($this->command, $this->inside_commend)) {
            $this->usages();
        }
        $this->paresParams();
    }

    /**
     * pares params
     */
    private function paresParams()
    {
        $func = $this->inside_func[$this->command];
        $this->$func();
    }


    /**
     * the func of -v
     */
    private function version()
    {
        echo "{$this->cli_name} \033[32m{$this->cli_version}\033[0m
";exit();
    }


    /**
     * run serve
     */
    private function serve()
    {
        //default params
        $port = '20002';
        $dirs = './webIndex';
        //show serv message
        echo "{$this->cli_name} {$this->cli_version}"."\n";
        echo 'This cli can only be used for development'."\n";
        echo 'Listening on http://localhost:'.$port."\n";
        echo 'Press Ctrl-Click url to website '."\n";
        echo 'Document index is '.__DIR__.ltrim($dirs,'.').$this->index."\n";
        echo "Simple find PID : `lsof -i:{$port}`"."\n";
        echo 'Press Ctrl-C to quit'."\n";
        //set shell command
        $command = "php -S localhost:{$port} -t {$dirs}";
        $this->runShell($command);
    }

    /**
     * @param string $msg
     * @param bool $stop
     */
    protected function format($msg = '', $stop = false)
    {
        if($msg) {
            echo $msg,"\n";
        }
        echo "\n";
        if($stop) {
            exit();
        }
    }

    /**
     * @param $command
     */
    protected function runShell($command)
    {
        shell_exec($command);
    }

    /**
     * show the shell usages
     */
    public function usages()
    {
        echo "{$this->cli_name} \033[32m{$this->cli_version}\033[0m

\033[33mUsage\033[0m:
  php devCli [options] [arguments]

\033[33mOptions\033[0m:
  \033[32m -h, --help \033[0m            Display this help message
  \033[32m -v, --version \033[0m         Display this application version
  \033[32m serv \033[0m                 Serve the application on the PHP development server
 
Available commands:
  \033[32m serv \033[0m                 Serve the application on the PHP development server
";exit();
    }
}

new devCli($argv);